### ISSUE TITLE
[Plugin / CompleteTheStash] TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by str0keR** [MinasukiHikimuna/MidnightRider-Stash#2]
Hi, what is this trying to tell me?
```
24-09-20 20:26:17Error   Plugin returned error: exit status 1
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash] TypeError: 'type' object is not subscriptable
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash]     def __init__(self, conn:dict={}, fragments:list[str]=[], verify_ssl:bool=True):
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash]   File "/usr/local/lib/python3.8/dist-packages/stashapi/stashapp.py", line 17, in StashInterface
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash]     class StashInterface(GQLWrapper):
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash]   File "/usr/local/lib/python3.8/dist-packages/stashapi/stashapp.py", line 13, in <module>
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash]     from stashapi.stashapp import StashInterface
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash]   File "/opt/stash/plugins/community/CompleteTheStash/LocalStashClient.py", line 1, in <module>
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash]     from LocalStashClient import LocalStashClient
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash]   File "plugins/community/CompleteTheStash/CompleteTheStash.py", line 8, in <module>
2024-09-20 20:26:17Error   [Plugin / CompleteTheStash] Traceback (most recent call last):
```

I'm running my primary instance of Stash on a Linux VM.
I'm running my secondary "missing" instance of Stash on the same Linux VM on a different port.
I've configured the plugin to connect to the "missing" stash via localhost:9998 (port used by missing stash)

**Comment by str0keR** [comment]
ok I fixed this myself.

* I was using Python3.8
* Upgraded to Python 3.10
* Reinstalled stashapp-tools using pip3 that's now using python 3.10
* Correctly configure missing stash as http://localhost:9998 (include the scheme, previously just had localhost:9998 - no "http://"
* run task
